name: Use Action

on:
  push:
    branches: ['main']

jobs:
  use-action:
    name: Use Action
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - uses: actions/checkout@v2

      # Minimal publish
      - uses: imjasonh/setup-ko@v0.2
      - run: ko publish --bare ./

      # Install an old release.
      - uses: imjasonh/setup-ko@v0.2
        with:
          version: v0.8.0
      - name: Check installed version
        run: ko version | grep 0.8.0

      # Install from tip
      - uses: imjasonh/setup-ko@v0.2
        with:
          version: tip
      - name: Check installed version (tip)
        run: |
          sudo rm /usr/local/bin/ko # Uninstall previous versions.
          ko version
